'use strict';
angular.module('sbAdminApp').constant('LawConfig', {
  httpCode: {//http请求常量
    SUCCESS: 200, //成功
    ERROR_REQUEST: 400, //错误请求。
    UNAUTHORIZED: 401, //未授权。
    PROHIBIT: 403, //禁止
    NOT_FOUND: 404, //未找到
    INTERNAL_ERROR: 500 //方法禁用
  },
  commonConstant: { //公用常量
    SUCCESS: 0,
    FAILURE: -1
  },
  serviceConstant:{//业务常量
    NET_ERROR:500,
    PHONE_CODE_ERROR:2007,
    PHONE_NOT_EXIST:3002,
    BIND_ERROR:3003
  },
  lawConstant: {//立案部分常量
    queryFilingListUrl: '/lawProject/adjust/queryFilingList',
    queryFilingCountUrl:'/lawProject/adjust/queryFilingCount',
    queryLawDetailUrl: '/lawProject/adjust/queryLawDetail',
    queryJyWorkFlowUrl: '/lawProject/adjust/queryJyWorkFlow',
    queryHandleLawListUrl:'/lawProject/adjust/queryHandleLawList',
    queryHandleLawCountUrl:"/lawProject/adjust/queryHandleLawCount",
    updateFilingInfoUrl: '/lawProject/adjust/updateFilingInfo',
    getUserListUrl: '/lawProject/system/getUserList',
    queryLawInfoUrl:'/lawProject/adjust/queryJyLawBySerialNo',
    saveLawCaseUrl:'/lawProject/adjust/saveJyLawInfo',
    buildWordUrl:'/lawProject/common/buildWord',
    removeApplicantUrl:'/lawProject/adjust/deleteJyLawApplyerInfo',
    removeAgentUrl:'/lawProject/adjust/deleteJyLawAgentInfo',
    getCommonInsuranceUrl:'/lawProject/adjust/queryGeneralInsurance',
    saveCommonInsuranceUrl:'/lawProject/adjust/updateGeneralInsurance',
    insertJyWorkFlowUrl:'/lawProject/common/insertJyWorkFlow',
    querySysUserByOrgIdUrl:'/lawProject/system/querySysUserByOrgId',
    queryOrgCourtByOrgIdUrl:'/lawProject/system/queryOrgCourtByOrgId',
    getCourtMediationMessageUrl:"/lawProject/adjust/getCourtMediation",
    insertCourtMediationMessageUrl:"/lawProject/adjust/insertCourtMediation",
    queryLawBindInfoUrl: "/lawProject/adjust/queryLawBindInfo",
    queryAllLawAdjustInfoUrl: "/lawProject/adjust/queryAllLawAdjustInfo",
    queryAllLawAdjustInfoCountUrl:"/lawProject/adjust/queryAllLawAdjustInfoCount",
    viewInstrumentUrl:"/lawProject/common/getDocumentFile",
    viewEmailSenderUrl:"/lawProject/common/queryJyEmailInfo",
    getEmailUrl:"/lawProject/common/getEmailUrl",
    isAgreeMediationUrl:"/lawProject/adjust/isAgreeMediation",
    endPretrialMediationUrl:"/lawProject/adjust/endPretrialMediation",
    restartMediationUrl:"/lawProject/adjust/restartMediation",
    applyForJudgeUrl:"/lawProject/adjust/applyForJudge",
    queryLawPayListUrl:"/lawProject/adjust/queryLawPayList",
    queryLawPayListCountUrl:"/lawProject/adjust/queryLawPayListCount",
    queryLawPayInfoUrl:"/lawProject/adjust/queryLawPayInfo",
    saveLawPayInfoUrl:"/lawProject/adjust/saveLawPayInfo",
    checkLawNoUrl:"/lawProject/adjust/checkLawNo",
    checkJudgeUserUrl:"/lawProject/adjust/checkJudgeUser",
    revokeCaseUrl:"/lawProject/adjust/revokeCase",
    createLawInfoCode:"/lawProject/adjust/createMediateLawInfoCode",
    lawCodeFileUrl:"/lawProject/common/codeFile/",
    queryIsApprovalCaseUrl:'/lawProject/adjust/queryIsApprovalCase',
    printDataUrl:"/lawProject/adjust/printData"
  },
  pictureConstant:{
    bigPictureUrl:"/lawProject/common/image/get/",
    smallPictureUrl:"/lawProject/common/image/getThumbnail/",
    uploadImageUrl:"/lawProject/common/uploadImage",
    cropImageUrl:"/lawProject/common/cropImage",
    uploadImageFileUrl:"/lawProject/common/uploadImageFile",
    getImageFileUrl:"/lawProject/common/getImageFile"
  },
  fileConstant:{
    uploadUrl:"/lawProject/common/coverDocumentFileById",
    uploadUrlByWordType:"/lawProject/common/coverDocumentFileByWordType",
    downloadInstrumentUrl:"/lawProject/common/downloadJyDocById",
    downloadInstrumentByWorkNoUrl:"/lawProject/common/downloadJyDocBySerialNoWordType",
    onlineCourtVideoUrl:"/lawProject/common/",
    isFileExistUrl:"/lawProject/common/isExistByDocId",
    isFilePageExistUrl:"/lawProject/common/isExistBySerialNoWordType",
    autoGenerateDocUrl:"/lawProject/common/buildJudicial",
    buildCivilMediationDocUrl:"/lawProject/common/buildCivilMediation"
  },
  massageConstant:{
    sendMessageUrl:"/lawProject/common/sendMessage",
    closedAdjustInfoUrl:"/lawProject/adjust/closedAdjustInfo",
    closedLawInfoUrl:"/lawProject/adjust/closedLawInfo ",
    sendEmailUrl:"/lawProject/common/sendEmail",
    getSingleLoginOnMailUrl:"/lawProject/common/getSingleLoginOnMail"
  },
  videoConstant:{
    joinRoomUrl:"/lawProject/common/joinRoom",
    viewCourtVideoUrl:"/lawProject/common/viewCourtVideo",
    sendEvidenceToVideoUrl:"/lawProject/common/resourceShow"
  }
});